name: mirror

on:
    workflow_call:
        inputs:
            repo:
                description: 'The repository to mirror'
                required: true
                type: string
            workspace:
                description: 'The workspace for the mirror'
                required: false
                type: string
                default: scidataexperts
            target_org:
                description: "Github org"
                required: false
                type: string
                default: USEPA
        secrets:
            BITBUCKET_TOKEN:
                    required: true
            MIRROR_PAT:
                    required: true

permissions: {}

jobs:
    mirror:
        runs-on: ubuntu-latest
        steps:
            - name: Mirror ${{ inputs.repo }}
              env:
                BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
                MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
                REPO: ${{ inputs.repo }}
                WORKSPACE: ${{ inputs.workspace }}
                TARGET_ORG: ${{ inputs.target_org }}
                GIT_TERMINAL_PROMPT: 0
              run: |
                set -euo pipefail
                git clone --bare --quiet \
                  "https://x-token-auth:${BITBUCKET_TOKEN}@bitbucket.org/${WORKSPACE}/${REPO}.git"
                cd -- "${REPO}.git"
                git push --mirror \
                  "https://x-access-token:${MIRROR_PAT}@github.com/${TARGET_ORG}/${REPO}.git"